PATIENTS_CACHE = None

ICD_DF_CACHE = None

ICD_OPTIONS_CACHE = None

ICD_LOOKUP_CACHE = None

DOCTORS_CACHE = None

LABS_CACHE = None

SCANS_CACHE = None

AVAILABLE_VISITS_CACHE = None

TIMETABLE_CACHE = None

PAYMENTS_CACHE = None

BOOKED_VISITS_CACHE = None

CURRENT_USER = None

ICD_CHRONIC_OPTIONS_CACHE = None

LABS_DF_CACHE = None
LABS_OPTIONS_CACHE = None
LABS_LOOKUP_CACHE = None

SCANS_DF_CACHE = None
SCANS_OPTIONS_CACHE = None
SCANS_LOOKUP_CACHE = None

OPENED_VISITS = []
SELECTED_VISIT = None